### ISSUE TITLE
Release Version 1.0.0

### ISSUE THREAD

**Issue by rufer7** [dfensgmbh/biz.dfch.CS.Examples.SampleAspNetWebApp#2]
**TODOs**
* [x] Release version `1.0.0` at GitHub 
* [x] Publish Web Application using VS2017
* [x] Add publish profile to GitHub repository
* [x] Upload Binaries to GitHub release
* [x] Extend README with manual that describes how to deploy the application (including config adjustments)
